kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: {{ .Chart.Name}}
spec:
  replicas: 1
  selector:
    matchLabels:
      run: {{ .Chart.Name}}
  template:
    metadata:
      labels: 
        run: {{ .Chart.Name}}
    spec:
      containers:
      - name: {{ .Chart.Name}}
        image: {{ .Values.image}}
        ports:
        - containerPort: 80
